image: node:10.15.3

pages:
  stage: deploy
  script:
    - npm i @compodoc/compodoc
    - npm run docs:build
    - npm run demo:build
    - cp -r docs/. public
  artifacts:
    paths:
      - public
  only:
    - master

